config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :users, only: [:new, :create] do
    resources :destinations, only: [:index]
  end

  get '/dashboard', to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
end

app/models/meetup_time.rb
class MeetupTime < ApplicationRecord
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :driver
  belongs_to :passenger
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :meetup_times
  belongs_to :destinations
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true
  validates :password, presence: true
  validates :password_confirmation, presence: true

  enum role: [:driver, :passenger]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authorized?

  def authorized?
    render file: 'public/404.html', status: 404 if current_user.nil?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < BaseController
  def index

  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def index
    @destinations = Destination.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    @user = User.find_by(email: params[:sessions][:email])
    if @user && @user.authenticate(params[:sessions][:password])
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash.now[:danger] = 'Unable to authorize user, please login or create an account'
      render :new
    end
  end

  def destroy
    user = User.find(current_user.id)
    if user.destroy
      session[:user_id] = nil
      redirect_to root_path
    else
      flash.now[:danger] = "Please try loggin out again"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(new_user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'Thank you for creating a new account'
      redirect_to dashboard_path
    else
      flash.now[:danger] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  private
    def new_user_params
      params.require(:user).permit(:name, :email, :phone, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<%= link_to 'Logout', logout_path, method: :delete %>
<div class="grd">
  <div class="grd-row">
    <div class="grd-row-col-3--sm">
    </div>
    <div class="grd-row-col-3-6--lg">
      <%= link_to 'Helpful Driver', root_path%>
    </div>
  </div>
</div>
<%= link_to 'Thankful Passenger', root_path %>

app/views/destinations/index.html.erb
<% @destinations.each do |destination| %>
  <%= destination.name %>
<% end %>

app/views/home/index.html.erb
<h1><%= link_to 'Login', login_path %></h1>
<h1><%= link_to 'Create a New Account', new_user_path %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeatsTaken</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <% flash.each do |type, msg| %>
    <div class="alert alert-<%="#{type} fade in" %>">
      <button class='close' data-dismiss='alert'>x</button>
      <%= msg %>
    </div>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>
 

app/views/users/new.html.erb
<h1>Create a New Account</h1>
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this account from being created:</h2>
        <% @user.errors.full_messages.each do |msg| %>
        <ul>
          <li><%= msg %></li>
        </ul>
        <% end %>
      </div>
    <% end %>

  <ul>
    <li>
      <%= f.label 'Name' %>
      <%= f.text_field :name %>
    </li>
    <li>

      <%= f.label 'Email' %>
      <%= f.text_field :email, type: 'email' %>
    </li>
    <li>
      <%= f.label 'Phone Number' %>
      <%= f.text_field :phone %>
    </li>
    <li>
      <%= f.label 'Password' %>
      <%= f.text_field :password, type: 'password' %>
    </li>
    <li>
      <%= f.label 'Password Confirmation' %>
      <%= f.text_field :password_confirmation, type: 'password' %>
    </li>
    <li>
      <%= f.submit 'Create Account' %>
    </li>
  </ul>
<% end %>